name: test
permissions:
  contents: read
  id-token: write
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    name: main
    steps:
      - name: Initiate OpenVPN
        env: 
          VPN_CONFIG: ${{ secrets.VPN_CONF }}
        run: |
          mkdir -p .github/ovpn
          echo $VPN_CONFIG | base64 -di > .github/ovpn/config.ovpn
          sudo apt install openvpn 
          sudo -b openvpn --config .github/ovpn/config.ovpn
          if ping -w 60 -c 1 192.168.1.1; then
            echo 'VPN Established'
          else
            echo 'VPN Failure'
            exit 1
          fi
      - name: Disconnect VPN
        run: sudo killall openvpn

